### ISSUE TITLE
Cant build esfx packages

### ISSUE THREAD

**Issue by vivekkj123** [esfx/esfx#9]
Hi there,

   While building the esfx packages, I got some errors. Those errors are given below. Please help me to build the module.
```
➜ node scripts/build.js 

➜gulp build
[18:14:44] Using gulpfile ~/Downloads/esfx/gulpfile.js
[18:14:44] Starting 'build'...
[18:14:44] Starting 'internal/assert'...
[18:14:44] Starting 'internal/binarysearch'...
[18:14:44] Starting 'internal/collections-hash'...
[18:14:44] Starting 'internal/deprecate'...
[18:14:44] Starting 'internal/guards'...
[18:14:44] Starting 'internal/hashcode'...
[18:14:44] Starting 'internal/integers'...
[18:14:44] Starting 'internal/jest-sequence'...
[18:14:44] Starting 'internal/murmur3'...
[18:14:44] Starting 'internal/tag'...
[18:14:44] Starting 'internal/threading'...
[18:14:44] Starting 'internal/ts-worker'...
[18:14:44] Starting 'packages/async'...
[18:14:44] Starting 'packages/async-autoresetevent'...
[18:14:44] Starting 'packages/async-barrier'...
[18:14:44] Starting 'packages/async-canceltoken'...
[18:14:44] Starting 'packages/async-conditionvariable'...
[18:14:44] Starting 'packages/async-countdown'...
[18:14:44] Starting 'packages/async-deferred'...
[18:14:44] Starting 'packages/async-delay'...
[18:14:44] Starting 'packages/async-iter'...
[18:14:44] Starting 'packages/async-iter-fn'...
[18:14:44] Starting 'packages/async-iter-fromsync'...
[18:14:44] Starting 'packages/async-iter-hierarchy'...
[18:14:44] Starting 'packages/async-iter-ordered'...
[18:14:44] Starting 'packages/async-iter-ordered-fromsync'...
[18:14:44] Starting 'packages/async-iter-query'...
[18:14:44] Starting 'packages/async-lazy'...
[18:14:44] Starting 'packages/async-lockable'...
[18:14:44] Starting 'packages/async-manualresetevent'...
[18:14:44] Starting 'packages/async-mutex'...
[18:14:44] Starting 'packages/async-queue'...
[18:14:44] Starting 'packages/async-readerwriterlock'...
[18:14:44] Starting 'packages/async-semaphore'...
[18:14:44] Starting 'packages/async-stack'...
[18:14:44] Starting 'packages/async-waitqueue'...
[18:14:44] Starting 'packages/cancelable'...
[18:14:44] Starting 'packages/cancelable-dom'...
[18:14:44] Starting 'packages/cancelable-dom-shim'...
[18:14:44] Starting 'packages/collection-core'...
[18:14:44] Starting 'packages/collection-core-dom-shim'...
[18:14:44] Starting 'packages/collection-core-shim'...
[18:14:44] Starting 'packages/collections'...
[18:14:44] Starting 'packages/collections-hashmap'...
[18:14:44] Starting 'packages/collections-hashset'...
[18:14:44] Starting 'packages/collections-linkedlist'...
[18:14:44] Starting 'packages/collections-multimap'...
[18:14:44] Starting 'packages/collections-sortedmap'...
[18:14:44] Starting 'packages/collections-sortedset'...
[18:14:44] Starting 'packages/decorators'...
[18:14:44] Starting 'packages/decorators-stage1-core'...
[18:14:44] Starting 'packages/disposable'...
[18:14:44] Starting 'packages/equatable'...
[18:14:44] Starting 'packages/equatable-shim'...
[18:14:44] Starting 'packages/events'...
[18:14:44] Starting 'packages/fn'...
[18:14:44] Starting 'packages/indexed-object'...
[18:14:44] Starting 'packages/interval'...
[18:14:44] Starting 'packages/iter'...
[18:14:44] Starting 'packages/iter-fn'...
[18:14:44] Starting 'packages/iter-grouping'...
[18:14:44] Starting 'packages/iter-hierarchy'...
[18:14:44] Starting 'packages/iter-lookup'...
[18:14:44] Starting 'packages/iter-ordered'...
[18:14:44] Starting 'packages/iter-page'...
[18:14:44] Starting 'packages/iter-query'...
[18:14:44] Starting 'packages/lazy'...
[18:14:44] Starting 'packages/metadata'...
[18:14:44] Starting 'packages/metadata-shim'...
[18:14:44] Starting 'packages/ref'...
[18:14:44] Starting 'packages/reflect-metadata-compat'...
[18:14:44] Starting 'packages/struct-type'...
[18:14:44] Starting 'packages/threading'...
[18:14:44] Starting 'packages/threading-autoresetevent'...
[18:14:44] Starting 'packages/threading-conditionvariable'...
[18:14:44] Starting 'packages/threading-countdown'...
[18:14:44] Starting 'packages/threading-lockable'...
[18:14:44] Starting 'packages/threading-manualresetevent'...
[18:14:44] Starting 'packages/threading-mutex'...
[18:14:44] Starting 'packages/threading-semaphore'...
[18:14:44] Starting 'packages/threading-sleep'...
[18:14:44] Starting 'packages/threading-spinwait'...
[18:14:44] Starting 'packages/type-model'...
packages/indexed-object/src/index.ts:131:5 - error TS2322: Type '(target: IntegerIndexedObject<any>) => PropertyKey[]' is not assignable to type '(target: IntegerIndexedObject<any>) => ArrayLike<string | symbol>'.
  Type 'PropertyKey[]' is not assignable to type 'ArrayLike<string | symbol>'.
    Index signatures are incompatible.
      Type 'PropertyKey' is not assignable to type 'string | symbol'.
        Type 'number' is not assignable to type 'string | symbol'.

131     ownKeys(target) {
        ~~~~~~~


Found 1 error.

[18:14:52] 'internal/assert' errored after 7.49 s
[18:14:52] Error: Process exited with code: 1
    at ChildProcess.<anonymous> (/home/vivek/Downloads/esfx/scripts/exec.js:27:24)
    at ChildProcess.emit (events.js:314:20)
    at ChildProcess.EventEmitter.emit (domain.js:506:15)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
    at Process.callbackTrampoline (internal/async_hooks.js:126:14)
[18:14:52] 'build' errored after 7.5 s
```

**Comment by vivekkj123** [comment]
@rbuckton

**Comment by rbuckton** [comment]
Thanks for the report, I'm looking into it.
